name: Build C++ Desktop App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install aqtinstall
      run: pip install aqtinstall==3.1.21

    - name: List available Qt modules
      run: |
        aqt list-qt windows desktop --modules 6.5.2 win64_msvc2019_64

    - name: Install Qt with base components
      uses: jurplel/install-qt-action@v3
      with:
        version: 6.5.2
        host: windows
        target: desktop
        arch: win64_msvc2019_64
        modules: qtbase  # Start with just qtbase, add more after verifying

    - name: Install build tools
      run: choco install cmake ninja -y

    - name: Configure project
      run: |
        mkdir build
        cd build
        cmake .. -G "Ninja" -DCMAKE_BUILD_TYPE=Release

    - name: Build project
      run: |
        cd build
        cmake --build . --config Release --parallel

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: built-app
        path: build/Release/BankApp.exe
